# Generated by Django 3.2.16 on 2023-06-13 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkUnit',
            fields=[
                ('unit_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OutputChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdout', models.TextField()),
                ('counter', models.IntegerField()),
                ('work_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reporter.workunit')),
            ],
        ),
    ]
